{% set name = "opentelemetry-instrumentation-mysql" %}
{% set version = "0.24b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-mysql-{{ version }}.tar.gz
  sha256: 6869d6cf796cae59d9c302ae0f0f689de46366d7dcd123b9b7e14ad7988d4376

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.24b0
    - opentelemetry-instrumentation-dbapi ==0.24b0
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - mysql-connector-python ~=8.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-mysql
  summary: OpenTelemetry MySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
