{% set name = "opentelemetry-instrumentation-mysql" %}
{% set version = "0.41b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_mysql-{{ version }}.tar.gz
  sha256: d9c6727ed0a2f2c4da2dab75c40e86fe10fbfc826443eb96a40c88a4caaa01ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-dbapi ==0.41b0
    - opentelemetry-instrumentation ==0.41b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-mysql
  summary: OpenTelemetry MySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
