{% set name = "opentelemetry-instrumentation-mysql" %}
{% set version = "0.26b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-mysql-{{ version }}.tar.gz
  sha256: 96854aaf2d6b0e4ca9a96043509bd1c05e1d1f5570031d5435175ff7bc7e09b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.26b1
    - opentelemetry-instrumentation-dbapi ==0.26b1
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test ==0.25b0
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test ==0.25b2
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.26b1
    # - mysql-connector-python ~=8.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-mysql
  summary: OpenTelemetry MySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
